# Generated by Django 4.2.2 on 2023-07-03 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Tigray', 'Tigray'), ('Dire Dawa', 'Dire Dawa'), ('Addis Ababa', 'Addis Ababa'), ('Harari ', 'Harari'), ('Gambella ', 'Gambella '), ('SNNPR', 'SNNPR'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Amhara', 'Amhara'), ('Afar', 'Afar')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('recipent', models.CharField(choices=[('Yourself', 'Yourself'), ('Someone else', 'Someone else'), ('Charity', 'Charit')], max_length=100)),
                ('category', models.CharField(choices=[('All campaigns', 'All campaigns'), ('Enviromental', 'Enviromental'), ('Medical', 'Medical'), ('Emergency', 'Emergency'), ('Education', 'Education')], max_length=100)),
                ('goal', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_donated', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gurshashareapp.campaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
