# Generated by Django 4.2.2 on 2023-07-08 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurshashareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(blank=True, choices=[('All campaigns', 'All campaigns'), ('Enviromental', 'Enviromental'), ('Medical', 'Medical'), ('Emergency', 'Emergency'), ('Education', 'Education')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='recipent',
            field=models.CharField(blank=True, choices=[('Yourself', 'Yourself'), ('Someone else', 'Someone else'), ('Charity', 'Charit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='state',
            field=models.CharField(blank=True, choices=[('Tigray', 'Tigray'), ('Dire Dawa', 'Dire Dawa'), ('Addis Ababa', 'Addis Ababa'), ('Harari ', 'Harari'), ('Gambella ', 'Gambella '), ('SNNPR', 'SNNPR'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Amhara', 'Amhara'), ('Afar', 'Afar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
