# Generated by Django 4.2.2 on 2023-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurshashareapp', '0004_alter_campaign_image_alter_campaign_recipent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
