# Generated by Django 4.2.2 on 2023-07-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gurshashareapp', '0005_alter_campaign_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='gurshashareapp.campaign'),
        ),
    ]
