# Generated by Django 4.2.2 on 2023-07-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurshashareapp', '0006_alter_donation_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
